import type { CashFlowRule, LineRule } from "../types/finance";

const TT99_B01 = "TT99/2025/TT-BTC Phụ lục IV - Mẫu B 01 - DN";
const TT99_B02 = "TT99/2025/TT-BTC Phụ lục IV - Mẫu B 02 - DN";
const TT99_B03 = "TT99/2025/TT-BTC Phụ lục IV - Mẫu B 03 - DN phương pháp trực tiếp";

export const b01Lines: LineRule[] = [
  { code: "100", label: "A - TÀI SẢN NGẮN HẠN", level: 0, bold: true, expression: "110+120+130+140+150+160", sourceRef: TT99_B01 },
  { code: "110", label: "I. Tiền và các khoản tương đương tiền", level: 1, bold: true, expression: "111+112", sourceRef: TT99_B01 },
  { code: "111", label: "1. Tiền", level: 2, accountPrefixes: ["111", "112", "113"], side: "balance", normalSide: "debit", sourceRef: TT99_B01 },
  { code: "112", label: "2. Các khoản tương đương tiền", level: 2, accountPrefixes: [], side: "balance", normalSide: "debit", sourceRef: TT99_B01, requiresManualMapping: true },
  { code: "120", label: "II. Đầu tư tài chính ngắn hạn", level: 1, bold: true, expression: "121+122+123+124+125+126", sourceRef: TT99_B01 },
  { code: "121", label: "1. Chứng khoán kinh doanh", level: 2, accountPrefixes: ["121"], side: "balance", normalSide: "debit", sourceRef: TT99_B01 },
  { code: "122", label: "2. Dự phòng giảm giá chứng khoán kinh doanh (*)", level: 2, accountPrefixes: ["2291"], side: "balance", normalSide: "credit", sign: -1, negative: true, sourceRef: TT99_B01 },
  { code: "123", label: "3. Đầu tư nắm giữ đến ngày đáo hạn ngắn hạn", level: 2, accountPrefixes: ["1281"], side: "balance", normalSide: "debit", sourceRef: TT99_B01 },
  { code: "124", label: "4. Dự phòng đầu tư nắm giữ đến ngày đáo hạn ngắn hạn (*)", level: 2, accountPrefixes: [], side: "balance", normalSide: "credit", sign: -1, negative: true, sourceRef: TT99_B01, requiresManualMapping: true, manualOnly: true },
  { code: "125", label: "5. Đầu tư ngắn hạn khác", level: 2, accountPrefixes: ["1288"], side: "balance", normalSide: "debit", sourceRef: TT99_B01 },
  { code: "126", label: "6. Dự phòng tổn thất các khoản đầu tư ngắn hạn khác (*)", level: 2, accountPrefixes: [], side: "balance", normalSide: "credit", sign: -1, negative: true, sourceRef: TT99_B01, requiresManualMapping: true, manualOnly: true },
  { code: "130", label: "III. Các khoản phải thu ngắn hạn", level: 1, bold: true, expression: "131+132+133+134+135+136+137", sourceRef: TT99_B01 },
  { code: "131", label: "1. Phải thu ngắn hạn của khách hàng", level: 2, accountPrefixes: ["131"], side: "balance", normalSide: "debit", sourceRef: TT99_B01, grossByCounterparty: true },
  { code: "132", label: "2. Trả trước cho người bán ngắn hạn", level: 2, accountPrefixes: ["331"], side: "balance", normalSide: "debit", sourceRef: TT99_B01, grossByCounterparty: true },
  { code: "133", label: "3. Phải thu nội bộ ngắn hạn", level: 2, accountPrefixes: ["136"], excludeAccountPrefixes: ["1361"], side: "balance", normalSide: "debit", sourceRef: TT99_B01 },
  { code: "134", label: "4. Phải thu theo tiến độ hợp đồng xây dựng", level: 2, accountPrefixes: ["337"], side: "balance", normalSide: "debit", sourceRef: TT99_B01 },
  { code: "135", label: "5. Phải thu ngắn hạn khác", level: 2, accountPrefixes: ["138", "141", "2441", "334", "338"], excludeAccountPrefixes: ["1381"], side: "balance", normalSide: "debit", sourceRef: TT99_B01, grossByCounterparty: true },
  { code: "136", label: "6. Dự phòng phải thu ngắn hạn khó đòi (*)", level: 2, accountPrefixes: ["2293"], side: "balance", normalSide: "credit", sign: -1, negative: true, sourceRef: TT99_B01 },
  { code: "137", label: "7. Tài sản thiếu chờ xử lý", level: 2, accountPrefixes: ["1381"], side: "balance", normalSide: "debit", sourceRef: TT99_B01 },
  { code: "140", label: "IV. Hàng tồn kho", level: 1, bold: true, expression: "141+142", sourceRef: TT99_B01 },
  { code: "141", label: "1. Hàng tồn kho", level: 2, accountPrefixes: ["151", "152", "153", "154", "155", "156", "157"], side: "balance", normalSide: "debit", sourceRef: TT99_B01 },
  { code: "142", label: "2. Dự phòng giảm giá hàng tồn kho (*)", level: 2, accountPrefixes: ["2294"], side: "balance", normalSide: "credit", sign: -1, negative: true, sourceRef: TT99_B01 },
  { code: "150", label: "V. Tài sản sinh học ngắn hạn", level: 1, bold: true, expression: "151+152+153", sourceRef: TT99_B01 },
  { code: "151", label: "1. Súc vật nuôi lấy sản phẩm một lần ngắn hạn", level: 2, accountPrefixes: [], side: "balance", normalSide: "debit", sourceRef: TT99_B01, requiresManualMapping: true, manualOnly: true },
  { code: "152", label: "2. Cây trồng theo mùa vụ hoặc lấy sản phẩm một lần ngắn hạn", level: 2, accountPrefixes: [], side: "balance", normalSide: "debit", sourceRef: TT99_B01, requiresManualMapping: true, manualOnly: true },
  { code: "153", label: "3. Dự phòng tổn thất tài sản sinh học ngắn hạn (*)", level: 2, accountPrefixes: [], side: "balance", normalSide: "credit", sign: -1, negative: true, sourceRef: TT99_B01, requiresManualMapping: true, manualOnly: true },
  { code: "160", label: "VI. Tài sản ngắn hạn khác", level: 1, bold: true, expression: "161+162+163+164+165", sourceRef: TT99_B01 },
  { code: "161", label: "1. Chi phí chờ phân bổ ngắn hạn", level: 2, accountPrefixes: ["2421"], side: "balance", normalSide: "debit", sourceRef: TT99_B01 },
  { code: "162", label: "2. Thuế GTGT được khấu trừ", level: 2, accountPrefixes: ["133"], side: "balance", normalSide: "debit", sourceRef: TT99_B01 },
  { code: "163", label: "3. Thuế và các khoản khác phải thu Nhà nước", level: 2, accountPrefixes: ["333"], side: "balance", normalSide: "debit", sourceRef: TT99_B01, grossByCounterparty: true },
  { code: "164", label: "4. Giao dịch mua bán lại trái phiếu Chính phủ", level: 2, accountPrefixes: ["171"], side: "balance", normalSide: "debit", sourceRef: TT99_B01 },
  { code: "165", label: "5. Tài sản ngắn hạn khác", level: 2, accountPrefixes: [], side: "balance", normalSide: "debit", sourceRef: TT99_B01, requiresManualMapping: true, manualOnly: true },
  { code: "200", label: "B - TÀI SẢN DÀI HẠN", level: 0, bold: true, expression: "210+220+230+240+250+260+270", sourceRef: TT99_B01 },
  { code: "210", label: "I. Các khoản phải thu dài hạn", level: 1, bold: true, expression: "211+212+213+214+215+216", sourceRef: TT99_B01 },
  { code: "211", label: "1. Phải thu dài hạn của khách hàng", level: 2, accountPrefixes: [], side: "balance", normalSide: "debit", sourceRef: TT99_B01, requiresManualMapping: true, manualOnly: true },
  { code: "212", label: "2. Trả trước cho người bán dài hạn", level: 2, accountPrefixes: [], side: "balance", normalSide: "debit", sourceRef: TT99_B01, requiresManualMapping: true, manualOnly: true },
  { code: "213", label: "3. Vốn kinh doanh ở đơn vị trực thuộc", level: 2, accountPrefixes: ["1361"], side: "balance", normalSide: "debit", sourceRef: TT99_B01, requiresManualMapping: true },
  { code: "214", label: "4. Phải thu nội bộ dài hạn", level: 2, accountPrefixes: [], side: "balance", normalSide: "debit", sourceRef: TT99_B01, requiresManualMapping: true, manualOnly: true },
  { code: "215", label: "5. Phải thu dài hạn khác", level: 2, accountPrefixes: ["2442"], side: "balance", normalSide: "debit", sourceRef: TT99_B01 },
  { code: "216", label: "6. Dự phòng phải thu dài hạn khó đòi (*)", level: 2, accountPrefixes: [], side: "balance", normalSide: "credit", sign: -1, negative: true, sourceRef: TT99_B01, requiresManualMapping: true, manualOnly: true },
  { code: "220", label: "II. Tài sản cố định", level: 1, bold: true, expression: "221+224+227", sourceRef: TT99_B01 },
  { code: "221", label: "1. Tài sản cố định hữu hình", level: 2, bold: true, expression: "222+223", sourceRef: TT99_B01 },
  { code: "222", label: "- Nguyên giá", level: 3, accountPrefixes: ["211"], side: "balance", normalSide: "debit", sourceRef: TT99_B01 },
  { code: "223", label: "- Giá trị hao mòn lũy kế (*)", level: 3, accountPrefixes: ["2141"], side: "balance", normalSide: "credit", sign: -1, negative: true, sourceRef: TT99_B01 },
  { code: "224", label: "2. Tài sản cố định thuê tài chính", level: 2, bold: true, expression: "225+226", sourceRef: TT99_B01 },
  { code: "225", label: "- Nguyên giá", level: 3, accountPrefixes: ["212"], side: "balance", normalSide: "debit", sourceRef: TT99_B01 },
  { code: "226", label: "- Giá trị hao mòn lũy kế (*)", level: 3, accountPrefixes: ["2142"], side: "balance", normalSide: "credit", sign: -1, negative: true, sourceRef: TT99_B01 },
  { code: "227", label: "3. Tài sản cố định vô hình", level: 2, bold: true, expression: "228+229", sourceRef: TT99_B01 },
  { code: "228", label: "- Nguyên giá", level: 3, accountPrefixes: ["213"], side: "balance", normalSide: "debit", sourceRef: TT99_B01 },
  { code: "229", label: "- Giá trị hao mòn lũy kế (*)", level: 3, accountPrefixes: ["2143"], side: "balance", normalSide: "credit", sign: -1, negative: true, sourceRef: TT99_B01 },
  { code: "230", label: "III. Tài sản sinh học dài hạn", level: 1, bold: true, expression: "231+236+237+238", sourceRef: TT99_B01 },
  { code: "231", label: "1. Súc vật nuôi cho sản phẩm định kỳ", level: 2, bold: true, expression: "232+233", sourceRef: TT99_B01 },
  { code: "232", label: "a) Súc vật nuôi cho sản phẩm định kỳ chưa đến giai đoạn trưởng thành", level: 3, accountPrefixes: ["21511"], side: "balance", normalSide: "debit", sourceRef: TT99_B01, requiresManualMapping: true },
  { code: "233", label: "b) Súc vật nuôi cho sản phẩm định kỳ đến giai đoạn trưởng thành", level: 3, bold: true, expression: "234+235", sourceRef: TT99_B01 },
  { code: "234", label: "- Nguyên giá", level: 4, accountPrefixes: ["21512"], side: "balance", normalSide: "debit", sourceRef: TT99_B01, requiresManualMapping: true },
  { code: "235", label: "- Giá trị khấu hao lũy kế (*)", level: 4, accountPrefixes: [], side: "balance", normalSide: "credit", sign: -1, negative: true, sourceRef: TT99_B01, requiresManualMapping: true, manualOnly: true },
  { code: "236", label: "2. Súc vật nuôi lấy sản phẩm một lần dài hạn", level: 2, accountPrefixes: [], side: "balance", normalSide: "debit", sourceRef: TT99_B01, requiresManualMapping: true, manualOnly: true },
  { code: "237", label: "3. Cây trồng theo mùa vụ hoặc lấy sản phẩm một lần dài hạn", level: 2, accountPrefixes: [], side: "balance", normalSide: "debit", sourceRef: TT99_B01, requiresManualMapping: true, manualOnly: true },
  { code: "238", label: "4. Dự phòng tổn thất tài sản sinh học dài hạn (*)", level: 2, accountPrefixes: [], side: "balance", normalSide: "credit", sign: -1, negative: true, sourceRef: TT99_B01, requiresManualMapping: true, manualOnly: true },
  { code: "240", label: "IV. Bất động sản đầu tư", level: 1, bold: true, expression: "241+242", sourceRef: TT99_B01 },
  { code: "241", label: "- Nguyên giá", level: 2, accountPrefixes: ["217"], side: "balance", normalSide: "debit", sourceRef: TT99_B01 },
  { code: "242", label: "- Giá trị hao mòn lũy kế (*)", level: 2, accountPrefixes: ["2147"], side: "balance", normalSide: "credit", sign: -1, negative: true, sourceRef: TT99_B01 },
  { code: "250", label: "V. Tài sản dở dang dài hạn", level: 1, bold: true, expression: "251+252", sourceRef: TT99_B01 },
  { code: "251", label: "1. Chi phí sản xuất, kinh doanh dở dang dài hạn", level: 2, accountPrefixes: [], side: "balance", normalSide: "debit", sourceRef: TT99_B01, requiresManualMapping: true, manualOnly: true },
  { code: "252", label: "2. Chi phí xây dựng cơ bản dở dang", level: 2, accountPrefixes: ["241"], side: "balance", normalSide: "debit", sourceRef: TT99_B01 },
  { code: "260", label: "VI. Đầu tư tài chính dài hạn", level: 1, bold: true, expression: "261+262+263+264+265+266", sourceRef: TT99_B01 },
  { code: "261", label: "1. Đầu tư vào công ty con", level: 2, accountPrefixes: ["221"], side: "balance", normalSide: "debit", sourceRef: TT99_B01 },
  { code: "262", label: "2. Đầu tư vào công ty liên doanh, liên kết", level: 2, accountPrefixes: ["222"], side: "balance", normalSide: "debit", sourceRef: TT99_B01 },
  { code: "263", label: "3. Đầu tư góp vốn vào đơn vị khác", level: 2, accountPrefixes: ["228"], side: "balance", normalSide: "debit", sourceRef: TT99_B01 },
  { code: "264", label: "4. Dự phòng tổn thất đầu tư vào đơn vị khác dài hạn (*)", level: 2, accountPrefixes: ["2292"], side: "balance", normalSide: "credit", sign: -1, negative: true, sourceRef: TT99_B01 },
  { code: "265", label: "5. Đầu tư nắm giữ đến ngày đáo hạn dài hạn", level: 2, accountPrefixes: [], side: "balance", normalSide: "debit", sourceRef: TT99_B01, requiresManualMapping: true, manualOnly: true },
  { code: "266", label: "6. Dự phòng đầu tư nắm giữ đến ngày đáo hạn dài hạn (*)", level: 2, accountPrefixes: [], side: "balance", normalSide: "credit", sign: -1, negative: true, sourceRef: TT99_B01, requiresManualMapping: true, manualOnly: true },
  { code: "270", label: "VII. Tài sản dài hạn khác", level: 1, bold: true, expression: "271+272+273+274", sourceRef: TT99_B01 },
  { code: "271", label: "1. Chi phí chờ phân bổ dài hạn", level: 2, accountPrefixes: ["2422"], side: "balance", normalSide: "debit", sourceRef: TT99_B01 },
  { code: "272", label: "2. Tài sản thuế thu nhập hoãn lại", level: 2, accountPrefixes: ["243"], side: "balance", normalSide: "debit", sourceRef: TT99_B01 },
  { code: "273", label: "3. Thiết bị, vật tư, phụ tùng thay thế dài hạn", level: 2, accountPrefixes: [], side: "balance", normalSide: "debit", sourceRef: TT99_B01, requiresManualMapping: true, manualOnly: true },
  { code: "274", label: "4. Tài sản dài hạn khác", level: 2, accountPrefixes: [], side: "balance", normalSide: "debit", sourceRef: TT99_B01, requiresManualMapping: true, manualOnly: true },
  { code: "280", label: "TỔNG CỘNG TÀI SẢN (280 = 100 + 200)", level: 0, bold: true, expression: "100+200", sourceRef: TT99_B01 },
  { code: "300", label: "C - NỢ PHẢI TRẢ", level: 0, bold: true, expression: "310+330", sourceRef: TT99_B01 },
  { code: "310", label: "I. Nợ ngắn hạn", level: 1, bold: true, expression: "311+312+313+314+315+316+317+318+319+320+321+322+323+324+325", sourceRef: TT99_B01 },
  { code: "311", label: "1. Phải trả người bán ngắn hạn", level: 2, accountPrefixes: ["331"], side: "balance", normalSide: "credit", sourceRef: TT99_B01, grossByCounterparty: true },
  { code: "312", label: "2. Người mua trả tiền trước ngắn hạn", level: 2, accountPrefixes: ["131"], side: "balance", normalSide: "credit", sourceRef: TT99_B01, grossByCounterparty: true },
  { code: "313", label: "3. Phải trả cổ tức, lợi nhuận", level: 2, accountPrefixes: ["332"], side: "balance", normalSide: "credit", sourceRef: TT99_B01 },
  { code: "314", label: "4. Thuế và các khoản phải nộp Nhà nước ngắn hạn", level: 2, accountPrefixes: ["333"], side: "balance", normalSide: "credit", sourceRef: TT99_B01, grossByCounterparty: true },
  { code: "315", label: "5. Phải trả người lao động", level: 2, accountPrefixes: ["334"], side: "balance", normalSide: "credit", sourceRef: TT99_B01, grossByCounterparty: true },
  { code: "316", label: "6. Chi phí phải trả ngắn hạn", level: 2, accountPrefixes: ["335"], side: "balance", normalSide: "credit", sourceRef: TT99_B01, requiresManualMapping: true },
  { code: "317", label: "7. Phải trả nội bộ ngắn hạn", level: 2, accountPrefixes: ["336"], excludeAccountPrefixes: ["3361"], side: "balance", normalSide: "credit", sourceRef: TT99_B01 },
  { code: "318", label: "8. Phải trả theo tiến độ hợp đồng xây dựng ngắn hạn", level: 2, accountPrefixes: ["337"], side: "balance", normalSide: "credit", sourceRef: TT99_B01 },
  { code: "319", label: "9. Doanh thu chờ phân bổ ngắn hạn", level: 2, accountPrefixes: ["3387"], side: "balance", normalSide: "credit", sourceRef: TT99_B01, requiresManualMapping: true },
  { code: "320", label: "10. Phải trả ngắn hạn khác", level: 2, accountPrefixes: ["138", "141", "2441", "338", "3441"], excludeAccountPrefixes: ["1381", "3387"], side: "balance", normalSide: "credit", sourceRef: TT99_B01, grossByCounterparty: true },
  { code: "321", label: "11. Vay và nợ thuê tài chính ngắn hạn", level: 2, accountPrefixes: ["3411"], side: "balance", normalSide: "credit", sourceRef: TT99_B01 },
  { code: "322", label: "12. Dự phòng phải trả ngắn hạn", level: 2, accountPrefixes: ["352"], side: "balance", normalSide: "credit", sourceRef: TT99_B01 },
  { code: "323", label: "13. Quỹ khen thưởng, phúc lợi", level: 2, accountPrefixes: ["353"], side: "balance", normalSide: "credit", sourceRef: TT99_B01 },
  { code: "324", label: "14. Quỹ bình ổn giá", level: 2, accountPrefixes: ["357"], side: "balance", normalSide: "credit", sourceRef: TT99_B01 },
  { code: "325", label: "15. Giao dịch mua bán lại trái phiếu Chính phủ", level: 2, accountPrefixes: ["171"], side: "balance", normalSide: "credit", sourceRef: TT99_B01 },
  { code: "330", label: "II. Nợ dài hạn", level: 1, bold: true, expression: "331+332+333+334+335+336+337+338+339+340+341+342+343+344", sourceRef: TT99_B01 },
  { code: "331", label: "1. Phải trả người bán dài hạn", level: 2, accountPrefixes: [], side: "balance", normalSide: "credit", sourceRef: TT99_B01, requiresManualMapping: true, manualOnly: true },
  { code: "332", label: "2. Người mua trả tiền trước dài hạn", level: 2, accountPrefixes: [], side: "balance", normalSide: "credit", sourceRef: TT99_B01, requiresManualMapping: true, manualOnly: true },
  { code: "333", label: "3. Thuế và các khoản phải nộp Nhà nước dài hạn", level: 2, accountPrefixes: [], side: "balance", normalSide: "credit", sourceRef: TT99_B01, requiresManualMapping: true, manualOnly: true },
  { code: "334", label: "4. Chi phí phải trả dài hạn", level: 2, accountPrefixes: [], side: "balance", normalSide: "credit", sourceRef: TT99_B01, requiresManualMapping: true, manualOnly: true },
  { code: "335", label: "5. Phải trả nội bộ về vốn kinh doanh", level: 2, accountPrefixes: ["3361"], side: "balance", normalSide: "credit", sourceRef: TT99_B01, requiresManualMapping: true },
  { code: "336", label: "6. Phải trả nội bộ dài hạn", level: 2, accountPrefixes: [], side: "balance", normalSide: "credit", sourceRef: TT99_B01, requiresManualMapping: true, manualOnly: true },
  { code: "337", label: "7. Doanh thu chờ phân bổ dài hạn", level: 2, accountPrefixes: [], side: "balance", normalSide: "credit", sourceRef: TT99_B01, requiresManualMapping: true, manualOnly: true },
  { code: "338", label: "8. Phải trả dài hạn khác", level: 2, accountPrefixes: ["3442"], side: "balance", normalSide: "credit", sourceRef: TT99_B01 },
  { code: "339", label: "9. Vay và nợ thuê tài chính dài hạn", level: 2, accountPrefixes: ["3412", "3431"], side: "balance", normalSide: "credit", sourceRef: TT99_B01 },
  { code: "340", label: "10. Trái phiếu chuyển đổi", level: 2, accountPrefixes: ["3432"], side: "balance", normalSide: "credit", sourceRef: TT99_B01 },
  { code: "341", label: "11. Cổ phiếu ưu đãi", level: 2, accountPrefixes: [], side: "balance", normalSide: "credit", sourceRef: TT99_B01, requiresManualMapping: true, manualOnly: true, nullWhenManual: true },
  { code: "342", label: "12. Thuế thu nhập hoãn lại phải trả", level: 2, accountPrefixes: ["347"], side: "balance", normalSide: "credit", sourceRef: TT99_B01 },
  { code: "343", label: "13. Dự phòng phải trả dài hạn", level: 2, accountPrefixes: [], side: "balance", normalSide: "credit", sourceRef: TT99_B01, requiresManualMapping: true, manualOnly: true },
  { code: "344", label: "14. Quỹ phát triển khoa học và công nghệ", level: 2, accountPrefixes: ["356"], side: "balance", normalSide: "credit", sourceRef: TT99_B01 },
  { code: "400", label: "D - VỐN CHỦ SỞ HỮU", level: 0, bold: true, expression: "411+412+413+414+415+416+417+418+419+420", sourceRef: TT99_B01 },
  { code: "411", label: "1. Vốn góp của chủ sở hữu", level: 1, bold: true, expression: "411a+411b", sourceRef: TT99_B01 },
  { code: "411a", label: "- Cổ phiếu phổ thông có quyền biểu quyết", level: 2, accountPrefixes: ["41111"], side: "balance", normalSide: "credit", sourceRef: TT99_B01 },
  { code: "411b", label: "- Cổ phiếu ưu đãi", level: 2, accountPrefixes: ["41112"], side: "balance", normalSide: "credit", sourceRef: TT99_B01 },
  { code: "412", label: "2. Thặng dư vốn", level: 1, accountPrefixes: ["4112"], side: "balance", normalSide: "credit", sourceRef: TT99_B01, requiresManualMapping: true },
  { code: "413", label: "3. Quyền chọn chuyển đổi trái phiếu", level: 1, accountPrefixes: ["4113"], side: "balance", normalSide: "credit", sourceRef: TT99_B01, requiresManualMapping: true },
  { code: "414", label: "4. Vốn khác của chủ sở hữu", level: 1, accountPrefixes: ["4118"], side: "balance", normalSide: "credit", sourceRef: TT99_B01, requiresManualMapping: true },
  { code: "415", label: "5. Cổ phiếu mua lại của chính mình (*)", level: 1, accountPrefixes: ["419"], side: "balance", normalSide: "debit", sign: -1, negative: true, sourceRef: TT99_B01 },
  { code: "416", label: "6. Chênh lệch đánh giá lại tài sản", level: 1, accountPrefixes: ["412"], side: "balance", normalSide: "credit", sourceRef: TT99_B01 },
  { code: "417", label: "7. Chênh lệch tỷ giá hối đoái", level: 1, accountPrefixes: ["413"], side: "balance", normalSide: "credit", sourceRef: TT99_B01 },
  { code: "418", label: "8. Quỹ đầu tư phát triển", level: 1, accountPrefixes: ["414"], side: "balance", normalSide: "credit", sourceRef: TT99_B01 },
  { code: "419", label: "9. Quỹ khác thuộc vốn chủ sở hữu", level: 1, accountPrefixes: ["418"], side: "balance", normalSide: "credit", sourceRef: TT99_B01 },
  { code: "420", label: "10. Lợi nhuận sau thuế chưa phân phối", level: 1, bold: true, expression: "420a+420b", sourceRef: TT99_B01 },
  { code: "420a", label: "- LNST chưa phân phối lũy kế đến cuối kỳ trước", level: 2, accountPrefixes: ["4211"], side: "balance", normalSide: "credit", sourceRef: TT99_B01 },
  { code: "420b", label: "- LNST chưa phân phối kỳ này", level: 2, accountPrefixes: ["4212"], side: "balance", normalSide: "credit", sourceRef: TT99_B01 },
  { code: "440", label: "TỔNG CỘNG NGUỒN VỐN (440 = 300 + 400)", level: 0, bold: true, expression: "300+400", sourceRef: TT99_B01 },
];

export const b02Lines: LineRule[] = [
  { code: "01", label: "1. Doanh thu bán hàng và cung cấp dịch vụ", level: 0, accountPrefixes: ["511"], excludeAccountPrefixes: ["5117"], side: "credit", sourceRef: TT99_B02 },
  { code: "02", label: "2. Các khoản giảm trừ doanh thu", level: 0, accountPrefixes: ["521"], side: "debit", sourceRef: TT99_B02 },
  { code: "10", label: "3. Doanh thu thuần về bán hàng và cung cấp dịch vụ (10 = 01 - 02)", level: 0, bold: true, expression: "01-02", sourceRef: TT99_B02 },
  { code: "11", label: "4. Giá vốn hàng bán", level: 0, accountPrefixes: ["632"], excludeAccountPrefixes: ["6327"], side: "debit", sourceRef: TT99_B02 },
  { code: "20", label: "5. Lợi nhuận gộp về bán hàng và cung cấp dịch vụ (20 = 10 - 11)", level: 0, bold: true, expression: "10-11", sourceRef: TT99_B02 },
  { code: "21", label: "6. Lãi/lỗ của hoạt động bán, thanh lý bất động sản đầu tư", level: 0, accountPrefixes: ["5117", "6327"], side: "credit", sourceRef: TT99_B02, requiresManualMapping: true },
  { code: "22", label: "7. Doanh thu hoạt động tài chính", level: 0, accountPrefixes: ["515"], side: "credit", sourceRef: TT99_B02 },
  { code: "23", label: "8. Chi phí tài chính", level: 0, accountPrefixes: ["635"], side: "debit", sourceRef: TT99_B02 },
  { code: "24", label: "Trong đó: Chi phí đi vay", level: 1, accountPrefixes: ["635411", "635412", "635413"], side: "debit", sourceRef: TT99_B02, requiresManualMapping: true },
  { code: "25", label: "9. Chi phí bán hàng", level: 0, accountPrefixes: ["641"], side: "debit", sourceRef: TT99_B02 },
  { code: "26", label: "10. Chi phí quản lý doanh nghiệp", level: 0, accountPrefixes: ["642"], side: "debit", sourceRef: TT99_B02 },
  { code: "30", label: "11. Lợi nhuận thuần từ hoạt động kinh doanh (30 = 20 + 21 + 22 - 23 - 25 - 26)", level: 0, bold: true, expression: "20+21+22-23-25-26", sourceRef: TT99_B02 },
  { code: "31", label: "12. Thu nhập khác", level: 0, accountPrefixes: ["711"], side: "credit", sourceRef: TT99_B02 },
  { code: "32", label: "13. Chi phí khác", level: 0, accountPrefixes: ["811"], side: "debit", sourceRef: TT99_B02 },
  { code: "40", label: "14. Lợi nhuận khác (40 = 31 - 32)", level: 0, bold: true, expression: "31-32", sourceRef: TT99_B02 },
  { code: "50", label: "15. Tổng lợi nhuận kế toán trước thuế (50 = 30 + 40)", level: 0, bold: true, expression: "30+40", sourceRef: TT99_B02 },
  { code: "51", label: "16. Chi phí thuế TNDN hiện hành", level: 0, accountPrefixes: ["8211"], side: "debit", sourceRef: TT99_B02 },
  { code: "52", label: "17. Chi phí thuế TNDN hoãn lại", level: 0, accountPrefixes: ["8212"], side: "debit", sourceRef: TT99_B02 },
  { code: "60", label: "18. Lợi nhuận sau thuế thu nhập doanh nghiệp (60 = 50 - 51 - 52)", level: 0, bold: true, expression: "50-51-52", sourceRef: TT99_B02 },
  { code: "70", label: "19. Lãi cơ bản trên cổ phiếu (*)", level: 0, accountPrefixes: [], sourceRef: TT99_B02, requiresManualMapping: true, manualOnly: true, nullWhenManual: true },
  { code: "71", label: "20. Lãi suy giảm trên cổ phiếu (*)", level: 0, accountPrefixes: [], sourceRef: TT99_B02, requiresManualMapping: true, manualOnly: true, nullWhenManual: true },
];

export const b03Lines: LineRule[] = [
  { code: "", label: "I. Lưu chuyển tiền từ hoạt động kinh doanh", level: 0, bold: true, sourceRef: TT99_B03 },
  { code: "01", label: "1. Tiền thu từ bán hàng, cung cấp dịch vụ và doanh thu khác", level: 1, sourceRef: TT99_B03 },
  { code: "02", label: "2. Tiền chi trả cho người cung cấp hàng hóa và dịch vụ", level: 1, negative: true, sourceRef: TT99_B03 },
  { code: "03", label: "3. Tiền chi trả cho người lao động", level: 1, negative: true, sourceRef: TT99_B03 },
  { code: "04", label: "4. Chi phí đi vay đã trả", level: 1, negative: true, sourceRef: TT99_B03 },
  { code: "05", label: "5. Thuế thu nhập doanh nghiệp đã nộp", level: 1, negative: true, sourceRef: TT99_B03 },
  { code: "06", label: "6. Tiền thu khác từ hoạt động kinh doanh", level: 1, sourceRef: TT99_B03 },
  { code: "07", label: "7. Tiền chi khác cho hoạt động kinh doanh", level: 1, negative: true, sourceRef: TT99_B03 },
  { code: "20", label: "Lưu chuyển tiền thuần từ hoạt động kinh doanh", level: 0, bold: true, expression: "01+02+03+04+05+06+07", sourceRef: TT99_B03 },
  { code: "", label: "II. Lưu chuyển tiền từ hoạt động đầu tư", level: 0, bold: true, sourceRef: TT99_B03 },
  { code: "21", label: "1. Tiền chi để mua sắm, xây dựng TSCĐ và các tài sản dài hạn khác", level: 1, negative: true, sourceRef: TT99_B03 },
  { code: "22", label: "2. Tiền thu từ thanh lý, nhượng bán TSCĐ và các tài sản dài hạn khác", level: 1, sourceRef: TT99_B03 },
  { code: "23", label: "3. Tiền chi cho vay, mua các công cụ nợ của đơn vị khác", level: 1, negative: true, sourceRef: TT99_B03 },
  { code: "24", label: "4. Tiền thu hồi cho vay, bán lại các công cụ nợ của đơn vị khác", level: 1, sourceRef: TT99_B03 },
  { code: "25", label: "5. Tiền chi đầu tư góp vốn vào đơn vị khác", level: 1, negative: true, sourceRef: TT99_B03 },
  { code: "26", label: "6. Tiền thu hồi đầu tư góp vốn vào đơn vị khác", level: 1, sourceRef: TT99_B03 },
  { code: "27", label: "7. Tiền thu lãi cho vay, cổ tức và lợi nhuận được chia", level: 1, sourceRef: TT99_B03 },
  { code: "30", label: "Lưu chuyển tiền thuần từ hoạt động đầu tư", level: 0, bold: true, expression: "21+22+23+24+25+26+27", sourceRef: TT99_B03 },
  { code: "", label: "III. Lưu chuyển tiền từ hoạt động tài chính", level: 0, bold: true, sourceRef: TT99_B03 },
  { code: "31", label: "1. Tiền thu từ phát hành cổ phiếu, nhận vốn góp của chủ sở hữu", level: 1, sourceRef: TT99_B03 },
  { code: "32", label: "2. Tiền trả lại vốn góp cho các chủ sở hữu, mua lại cổ phiếu đã phát hành", level: 1, negative: true, sourceRef: TT99_B03 },
  { code: "33", label: "3. Tiền thu từ đi vay", level: 1, sourceRef: TT99_B03 },
  { code: "34", label: "4. Tiền trả nợ gốc vay", level: 1, negative: true, sourceRef: TT99_B03 },
  { code: "35", label: "5. Tiền trả nợ gốc thuê tài chính", level: 1, negative: true, sourceRef: TT99_B03 },
  { code: "36", label: "6. Cổ tức, lợi nhuận đã trả cho chủ sở hữu", level: 1, negative: true, sourceRef: TT99_B03 },
  { code: "40", label: "Lưu chuyển tiền thuần từ hoạt động tài chính", level: 0, bold: true, expression: "31+32+33+34+35+36", sourceRef: TT99_B03 },
  { code: "50", label: "Lưu chuyển tiền thuần trong kỳ (50 = 20+30+40)", level: 0, bold: true, expression: "20+30+40", sourceRef: TT99_B03 },
  { code: "60", label: "Tiền và tương đương tiền đầu kỳ", level: 0, bold: true, sourceRef: TT99_B03 },
  { code: "61", label: "Ảnh hưởng của thay đổi tỷ giá hối đoái quy đổi ngoại tệ", level: 0, sourceRef: TT99_B03, requiresManualMapping: true },
  { code: "70", label: "Tiền và tương đương tiền cuối kỳ (70 = 50+60+61)", level: 0, bold: true, expression: "50+60+61", sourceRef: TT99_B03 },
];

const legacyCashFlowRules: CashFlowRule[] = [
  { code: "01", direction: "in", oppositeAccountPrefixes: ["511", "33311", "131", "121"], textIncludes: ["khách hàng", "customer", "invoice", "bán hàng", "doanh thu"], sourceRef: TT99_B03 },
  { code: "02", direction: "out", oppositeAccountPrefixes: ["121", "133", "151", "152", "153", "154", "155", "156", "157", "331", "621", "622", "627", "632", "641", "642"], textIncludes: ["nhà cung cấp", "supplier", "mua hàng", "giá vốn", "dịch vụ", "chi phí quản lý"], sourceRef: TT99_B03 },
  { code: "03", direction: "out", oppositeAccountPrefixes: ["334", "3382", "3383", "3384", "3385", "3386"], textIncludes: ["lương", "nhân viên", "salary", "payroll"], sourceRef: TT99_B03 },
  { code: "04", direction: "out", oppositeAccountPrefixes: ["335", "635"], textIncludes: ["lãi vay", "interest"], sourceRef: TT99_B03 },
  { code: "05", direction: "out", oppositeAccountPrefixes: ["3334", "821"], textIncludes: ["thuế tndn"], sourceRef: TT99_B03 },
  { code: "21", direction: "out", oppositeAccountPrefixes: ["211", "212", "213", "217", "241"], textIncludes: ["tài sản cố định", "tscđ", "xây dựng"], sourceRef: TT99_B03 },
  { code: "22", direction: "in", oppositeAccountPrefixes: ["211", "212", "213", "217", "711"], textIncludes: ["thanh lý", "nhượng bán"], sourceRef: TT99_B03 },
  { code: "23", direction: "out", oppositeAccountPrefixes: ["128", "228"], textIncludes: ["cho vay", "mua công cụ nợ"], sourceRef: TT99_B03 },
  { code: "24", direction: "in", oppositeAccountPrefixes: ["128", "228"], textIncludes: ["thu hồi cho vay", "bán công cụ nợ"], sourceRef: TT99_B03 },
  { code: "25", direction: "out", oppositeAccountPrefixes: ["221", "222", "228"], textIncludes: ["góp vốn", "đầu tư"], sourceRef: TT99_B03 },
  { code: "26", direction: "in", oppositeAccountPrefixes: ["221", "222", "228"], textIncludes: ["thu hồi đầu tư"], sourceRef: TT99_B03 },
  { code: "27", direction: "in", oppositeAccountPrefixes: ["515", "138"], textIncludes: ["lãi cho vay", "cổ tức", "lợi nhuận được chia"], sourceRef: TT99_B03 },
  { code: "31", direction: "in", oppositeAccountPrefixes: ["411"], textIncludes: ["góp vốn", "phát hành cổ phiếu"], sourceRef: TT99_B03 },
  { code: "32", direction: "out", oppositeAccountPrefixes: ["411", "419"], textIncludes: ["trả lại vốn", "mua lại cổ phiếu"], sourceRef: TT99_B03 },
  { code: "33", direction: "in", oppositeAccountPrefixes: ["341"], textIncludes: ["vay", "giải ngân"], sourceRef: TT99_B03 },
  { code: "34", direction: "out", oppositeAccountPrefixes: ["341"], textIncludes: ["trả nợ vay", "gốc vay"], sourceRef: TT99_B03 },
  { code: "35", direction: "out", oppositeAccountPrefixes: ["3412", "315"], textIncludes: ["thuê tài chính"], sourceRef: TT99_B03 },
  { code: "36", direction: "out", oppositeAccountPrefixes: ["421"], textIncludes: ["cổ tức", "lợi nhuận đã trả"], sourceRef: TT99_B03 },
  { code: "06", direction: "in", oppositeAccountPrefixes: ["141"], textIncludes: ["thu khác"], sourceRef: TT99_B03 },
  { code: "07", direction: "out", oppositeAccountPrefixes: ["338"], textIncludes: ["chi khác"], sourceRef: TT99_B03 },
  { code: "01", direction: "out", oppositeAccountPrefixes: ["131"], textIncludes: [], sourceRef: TT99_B03 },
  { code: "06", direction: "out", oppositeAccountPrefixes: ["141"], textIncludes: [], sourceRef: TT99_B03 },
  { code: "07", direction: "in", oppositeAccountPrefixes: ["338"], textIncludes: [], sourceRef: TT99_B03 },
];

export const cashFlowRules: CashFlowRule[] = [
  { code: "06", direction: "in", oppositeAccountPrefixes: ["344111"], textIncludes: ["nhan ky quy", "nhan ky cuoc"], sourceRef: TT99_B03 },
  { code: "02", direction: "in", oppositeAccountPrefixes: ["641712"], textIncludes: ["hoan chi phi ban hang", "hoan chi phi dich vu"], sourceRef: TT99_B03 },
  { code: "01", direction: "in", oppositeAccountPrefixes: ["511", "33311", "131", "121"], textIncludes: ["khach hang", "customer", "invoice", "ban hang", "doanh thu"], sourceRef: TT99_B03 },
  { code: "02", direction: "in", oppositeAccountPrefixes: ["331"], textIncludes: ["hoan tien nha cung cap", "hoan ung nha cung cap"], sourceRef: TT99_B03 },
  { code: "06", direction: "in", oppositeAccountPrefixes: ["138", "244", "338", "711", "141"], textIncludes: ["thu khac"], sourceRef: TT99_B03 },
  { code: "33", direction: "in", oppositeAccountPrefixes: ["341"], textIncludes: ["vay", "giai ngan"], sourceRef: TT99_B03 },
  { code: "27", direction: "in", oppositeAccountPrefixes: ["515111"], textIncludes: ["lai cho vay", "lai tien gui co ky han", "co tuc", "loi nhuan duoc chia"], sourceRef: TT99_B03 },
  { code: "22", direction: "in", oppositeAccountPrefixes: ["211", "212", "213", "217"], textIncludes: ["thanh ly", "nhuong ban"], sourceRef: TT99_B03 },
  { code: "24", direction: "in", oppositeAccountPrefixes: ["128", "228"], textIncludes: ["thu hoi cho vay", "ban cong cu no"], sourceRef: TT99_B03 },
  { code: "26", direction: "in", oppositeAccountPrefixes: ["221", "222", "228"], textIncludes: ["thu hoi dau tu"], sourceRef: TT99_B03 },
  { code: "31", direction: "in", oppositeAccountPrefixes: ["411"], textIncludes: ["gop von", "phat hanh co phieu"], sourceRef: TT99_B03 },
  { code: "02", direction: "out", oppositeAccountPrefixes: ["121", "133", "151", "152", "153", "154", "155", "156", "157", "331", "621", "622", "627", "632", "641", "642"], textIncludes: ["nha cung cap", "mua hang", "gia von", "dich vu", "chi phi quan ly"], sourceRef: TT99_B03 },
  { code: "07", direction: "out", oppositeAccountPrefixes: ["344111"], textIncludes: ["tra lai ky quy", "tra lai ky cuoc"], sourceRef: TT99_B03 },
  { code: "03", direction: "out", oppositeAccountPrefixes: ["334", "3382", "3383", "3384", "3385", "3386"], textIncludes: ["luong", "nhan vien", "salary", "payroll"], sourceRef: TT99_B03 },
  { code: "04", direction: "out", oppositeAccountPrefixes: ["635"], textIncludes: ["lai vay", "interest"], sourceRef: TT99_B03 },
  { code: "05", direction: "out", oppositeAccountPrefixes: ["3334", "821"], textIncludes: ["thue tndn"], sourceRef: TT99_B03 },
  { code: "07", direction: "out", oppositeAccountPrefixes: ["333"], excludeAccountPrefixes: ["3334"], textIncludes: ["thue", "phi", "le phi"], sourceRef: TT99_B03 },
  { code: "07", direction: "out", oppositeAccountPrefixes: ["138", "244", "338"], textIncludes: ["chi khac"], sourceRef: TT99_B03 },
  { code: "21", direction: "out", oppositeAccountPrefixes: ["211", "212", "213", "217", "241"], textIncludes: ["tai san co dinh", "tscd", "xay dung"], sourceRef: TT99_B03 },
  { code: "01", direction: "out", oppositeAccountPrefixes: ["131"], textIncludes: [], sourceRef: TT99_B03 },
  { code: "23", direction: "out", oppositeAccountPrefixes: ["128", "228"], textIncludes: ["cho vay", "mua cong cu no"], sourceRef: TT99_B03 },
  { code: "25", direction: "out", oppositeAccountPrefixes: ["221", "222", "228"], textIncludes: ["gop von", "dau tu"], sourceRef: TT99_B03 },
  { code: "32", direction: "out", oppositeAccountPrefixes: ["411", "419"], textIncludes: ["tra lai von", "mua lai co phieu"], sourceRef: TT99_B03 },
  { code: "34", direction: "out", oppositeAccountPrefixes: ["341"], textIncludes: ["tra no vay", "goc vay"], sourceRef: TT99_B03 },
  { code: "35", direction: "out", oppositeAccountPrefixes: ["3412", "315"], textIncludes: ["thue tai chinh"], sourceRef: TT99_B03 },
  { code: "36", direction: "out", oppositeAccountPrefixes: ["421"], textIncludes: ["co tuc", "loi nhuan da tra"], sourceRef: TT99_B03 },
  { code: "06", direction: "out", oppositeAccountPrefixes: ["141"], textIncludes: [], sourceRef: TT99_B03 },
];
